# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
