# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161114_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='users',
        ),
        migrations.DeleteModel(
            name='Usergroup',
        ),
    ]
